title: Siren's Docs
description: Docs for Sirens Hytale Mods!
theme: just-the-docs

url: https://www.mermaids.dev

aux_links:
  Mermaids Mod: https://www.curseforge.com/hytale/mods/mermaids
  Marriage Mod: https://www.curseforge.com/hytale/mods/marriage
  Discord: https://discord.gg/ZFT3C9aKjZ

aux_links_new_tab: true

color_scheme: dark

logo: "/assets/images/siren-logo.png"
favicon_ico: "/assets/images/siren-logo.ico"
