title: Siren's Hytale Mods Docs
description: Docs for Sirens Hytale Mods!
theme: just-the-docs

url: https://mefroggy.github.io/siren

aux_links:
  Mermaids Mod: https://www.curseforge.com/hytale/mods/mermaids
  Marriage Mod: https://www.curseforge.com/hytale/mods/marriage

aux_links_new_tab: true

color_scheme: dark

logo: "/assets/images/siren-logo.png"
favicon_ico: "/assets/images/siren-logo.ico"
