title: Sirens Hytale Mods
description: Docs for Sirens Hytale Mods!
theme: just-the-docs

url: https://mefroggy.github.io/sirenhytale

aux_links:
  Mermaids: https://www.curseforge.com/hytale/mods/mermaids
  Marriage: https://www.curseforge.com/hytale/mods/marriage
