title: Siren's Docs
description: Docs for Siren's Hytale Mods!
theme: just-the-docs

url: https://www.mermaids.dev

aux_links:
  Curseforge: https://www.curseforge.com/members/sirenhytale/projects
  Mermaids Download: https://www.curseforge.com/hytale/mods/mermaids/files/all?page=1&pageSize=20&showAlphaFiles=show
  Marriage Download: https://www.curseforge.com/hytale/mods/marriage/files/all?page=1&pageSize=20&showAlphaFiles=show
  Discord: https://discord.gg/ZFT3C9aKjZ

aux_links_new_tab: true

color_scheme: dark

logo: "/assets/images/utils/siren-logo.png"
favicon_ico: "/assets/images/utils/siren-logo.ico"

back_to_top: true
back_to_top_text: "Back to top"
