title: Sirens Hytale Mods
description: Docs for Sirens Hytale Mods!
theme: just-the-docs

url: https://sirenhytale.github.io

aux_links:
  Template Repository: https://github.com/meFroggy/sirenhytale
